defaults:
  - optimizer: adamw
  - scheduler: cosine_annealing_lr
  - _self_

epoch: 150
ema: True
wandb: True
log_interval: 50
save_interval: 50
dataloader:
  batch_size: 64
  shuffle: True
  num_workers: 4
  pin_memory: True
  drop_last: True
val:
  interval: 10
  dataloader:
    batch_size: 64
    shuffle: False
    num_workers: 4
    pin_memory: True
    drop_last: False
